# Site settings
title: Diogo Friggo's site
description: A blog about software development and everything else I'm interested in
baseurl:
url: "https://diogofriggo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Diogo Friggo
user_description:
user_title: Software Developer <br/> & <br/> Wind Energy Engineer at <a class="banner-link" href="https://www.dnv.com/">DNV</a>
email: diogofriggobr@gmail.com
twitter_username:
github_username:  diogofriggo
gplus_username:
disqus_username: diogofriggo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: About me
    url: /
  - title: Contact
    url: /contact
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
